### ISSUE TITLE
Previews for Builder

### ISSUE THREAD

**Issue by distantnative** [getkirby/demokit#26]
(or if there is an option to disable the preview button)

**Comment by bastianallgeier** [comment]
??? There are previews for all builder modules.

**Comment by distantnative** [comment]
Those previews look very broken to me:
<img width="1130" alt="Screen Shot 2020-02-05 at 21 57 28" src="https://user-images.githubusercontent.com/3788865/73882528-88f56580-4862-11ea-9a0e-81ed2bda1c84.png">

**Comment by bastianallgeier** [comment]
Oh, it seems that the css file is not properly loaded on the demo server.

**Comment by lukasbestle** [comment]
Maybe because the instances are installed in a subfolder?

**Comment by bastianallgeier** [comment]
✅ 

There was an issue in the builder with css files in subfolders. I just fixed that.
