### ISSUE TITLE
Menu is open by default on Microsoft Edge

### ISSUE THREAD

**Issue by afbora** [getkirby/demokit#36]
Menu is open by default on Microsoft Edge browser and nothing happens (hide/show) when clicked. If the Edge browser is not important, you can close the issue 😄 

![image (8)](https://user-images.githubusercontent.com/3393422/74088359-cea27000-4aa6-11ea-83b7-beface7b8869.jpg)

**Comment by afbora** [comment]
I learned that the edge browser does not support the `open` attribute. If we do not plan to solve it in a different way, you can close the issue.

![FireShot Capture 034 - {details}_ The Details disclosure element - HTML_ Hypertext Markup La_ - developer mozilla org](https://user-images.githubusercontent.com/3393422/74543784-0dc53b00-4f57-11ea-9587-a88ee01e4b30.png)

**Documentation**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by bastianallgeier** [comment]
Hm, looks like I have to switch or add a notice that we don't support edge.

**Comment by afbora** [comment]
To give you an idea: https://github.com/rstacruz/details-polyfill

**Comment by afbora** [comment]
Now Edge browser supports the `<details>`

![screen-capture-1058-{details}_ The Details disclosure element - HTML_ HyperText Markup Languag_-developer mozilla org](https://user-images.githubusercontent.com/3393422/117801722-4ab4d600-b25d-11eb-99c7-3838656c1f88.png)
