### ISSUE TITLE
Code area not responsive

### ISSUE THREAD

**Issue by afbora** [getkirby/demokit#39]
![Screenshot_20200213-222345_Chrome](https://user-images.githubusercontent.com/3393422/74470469-aacc9900-4eaf-11ea-9be3-f2ec10275ff6.jpg)

![Screenshot_20200213-222907_Chrome](https://user-images.githubusercontent.com/3393422/74470849-4bbb5400-4eb0-11ea-9122-bd6547638561.jpg)

We need to enable horizontal scrolling on mobile.

**Comment by lukasbestle** [comment]
✅
